// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/proto/web3.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Web3Service_GetBlockHeight_FullMethodName = "/proto.Web3Service/GetBlockHeight"
)

// Web3ServiceClient is the client API for Web3Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义 Web3 服务接口
type Web3ServiceClient interface {
	// 定义一个方法: 输入 ChainID，返回高度
	GetBlockHeight(ctx context.Context, in *GetBlockHeightRequest, opts ...grpc.CallOption) (*GetBlockHeightResponse, error)
}

type web3ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeb3ServiceClient(cc grpc.ClientConnInterface) Web3ServiceClient {
	return &web3ServiceClient{cc}
}

func (c *web3ServiceClient) GetBlockHeight(ctx context.Context, in *GetBlockHeightRequest, opts ...grpc.CallOption) (*GetBlockHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockHeightResponse)
	err := c.cc.Invoke(ctx, Web3Service_GetBlockHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Web3ServiceServer is the server API for Web3Service service.
// All implementations must embed UnimplementedWeb3ServiceServer
// for forward compatibility.
//
// 定义 Web3 服务接口
type Web3ServiceServer interface {
	// 定义一个方法: 输入 ChainID，返回高度
	GetBlockHeight(context.Context, *GetBlockHeightRequest) (*GetBlockHeightResponse, error)
	mustEmbedUnimplementedWeb3ServiceServer()
}

// UnimplementedWeb3ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeb3ServiceServer struct{}

func (UnimplementedWeb3ServiceServer) GetBlockHeight(context.Context, *GetBlockHeightRequest) (*GetBlockHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockHeight not implemented")
}
func (UnimplementedWeb3ServiceServer) mustEmbedUnimplementedWeb3ServiceServer() {}
func (UnimplementedWeb3ServiceServer) testEmbeddedByValue()                     {}

// UnsafeWeb3ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Web3ServiceServer will
// result in compilation errors.
type UnsafeWeb3ServiceServer interface {
	mustEmbedUnimplementedWeb3ServiceServer()
}

func RegisterWeb3ServiceServer(s grpc.ServiceRegistrar, srv Web3ServiceServer) {
	// If the following call pancis, it indicates UnimplementedWeb3ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Web3Service_ServiceDesc, srv)
}

func _Web3Service_GetBlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Web3ServiceServer).GetBlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web3Service_GetBlockHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Web3ServiceServer).GetBlockHeight(ctx, req.(*GetBlockHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Web3Service_ServiceDesc is the grpc.ServiceDesc for Web3Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Web3Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Web3Service",
	HandlerType: (*Web3ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockHeight",
			Handler:    _Web3Service_GetBlockHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/web3.proto",
}
