// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/web3.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义请求参数
type GetBlockHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeightRequest) Reset() {
	*x = GetBlockHeightRequest{}
	mi := &file_api_proto_web3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeightRequest) ProtoMessage() {}

func (x *GetBlockHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_web3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeightRequest.ProtoReflect.Descriptor instead.
func (*GetBlockHeightRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_web3_proto_rawDescGZIP(), []int{0}
}

func (x *GetBlockHeightRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// 定义返回结果
type GetBlockHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       int64                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height        int64                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeightResponse) Reset() {
	*x = GetBlockHeightResponse{}
	mi := &file_api_proto_web3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeightResponse) ProtoMessage() {}

func (x *GetBlockHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_web3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeightResponse.ProtoReflect.Descriptor instead.
func (*GetBlockHeightResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_web3_proto_rawDescGZIP(), []int{1}
}

func (x *GetBlockHeightResponse) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetBlockHeightResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_api_proto_web3_proto protoreflect.FileDescriptor

const file_api_proto_web3_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/web3.proto\x12\x05proto\"2\n" +
	"\x15GetBlockHeightRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\"K\n" +
	"\x16GetBlockHeightResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x03R\achainId\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x03R\x06height2\\\n" +
	"\vWeb3Service\x12M\n" +
	"\x0eGetBlockHeight\x12\x1c.proto.GetBlockHeightRequest\x1a\x1d.proto.GetBlockHeightResponseB7Z5github.com/zy99978455-otw/go-micro-template/api/protob\x06proto3"

var (
	file_api_proto_web3_proto_rawDescOnce sync.Once
	file_api_proto_web3_proto_rawDescData []byte
)

func file_api_proto_web3_proto_rawDescGZIP() []byte {
	file_api_proto_web3_proto_rawDescOnce.Do(func() {
		file_api_proto_web3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_web3_proto_rawDesc), len(file_api_proto_web3_proto_rawDesc)))
	})
	return file_api_proto_web3_proto_rawDescData
}

var file_api_proto_web3_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_web3_proto_goTypes = []any{
	(*GetBlockHeightRequest)(nil),  // 0: proto.GetBlockHeightRequest
	(*GetBlockHeightResponse)(nil), // 1: proto.GetBlockHeightResponse
}
var file_api_proto_web3_proto_depIdxs = []int32{
	0, // 0: proto.Web3Service.GetBlockHeight:input_type -> proto.GetBlockHeightRequest
	1, // 1: proto.Web3Service.GetBlockHeight:output_type -> proto.GetBlockHeightResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_web3_proto_init() }
func file_api_proto_web3_proto_init() {
	if File_api_proto_web3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_web3_proto_rawDesc), len(file_api_proto_web3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_web3_proto_goTypes,
		DependencyIndexes: file_api_proto_web3_proto_depIdxs,
		MessageInfos:      file_api_proto_web3_proto_msgTypes,
	}.Build()
	File_api_proto_web3_proto = out.File
	file_api_proto_web3_proto_goTypes = nil
	file_api_proto_web3_proto_depIdxs = nil
}
